version: '3.8'

services:
  # Serviço MongoDB com replicação
  mongo:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    entrypoint: /bin/sh -c "chmod 400 /tmp/keyfile && mongod --replSet rs0 --bind_ip_all --keyFile /tmp/keyfile"
    volumes:
      - mongo_data:/data/db
      - ./keyfile:/tmp/keyfile
    ports:
      - "27017:27017"
    networks:
      - mean_net

  # Serviço MongoDB (réplica 1)
  mongo_replica_1:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    entrypoint: /bin/sh -c "chmod 400 /tmp/keyfile && mongod --replSet rs0 --bind_ip_all --keyFile /tmp/keyfile"
    volumes:
      - mongo_replica1_data:/data/db
      - ./keyfile:/tmp/keyfile
    ports:
      - "27018:27017"
    networks:
      - mean_net

  # Serviço MongoDB (réplica 2)
  mongo_replica_2:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    entrypoint: /bin/sh -c "chmod 400 /tmp/keyfile && mongod --replSet rs0 --bind_ip_all --keyFile /tmp/keyfile"
    volumes:
      - mongo_replica2_data:/data/db
      - ./keyfile:/tmp/keyfile
    ports:
      - "27019:27017"
    networks:
      - mean_net

  # Serviço do backend (Node.js + Express)
  backend:
    build:
      context: ../backEnd
      dockerfile: dockerFile
    environment:
      MONGO_URL: mongodb://root:password@mongo:27017,mongo_replica_1:27017,mongo_replica_2:27017/meancrud?replicaSet=rs0&authSource=admin
    networks:
      - mean_net
    depends_on:
      - mongo
      - mongo_replica_1
      - mongo_replica_2

  # Serviço do frontend (Angular)
  frontend:
    build:
      context: ../frontEnd
      dockerfile: dockerFile
    ports:
      - "4200:80"
    networks:
      - mean_net
    depends_on:
      - backend

networks:
  mean_net:
    driver: bridge

volumes:
  mongo_data:
  mongo_replica1_data:
  mongo_replica2_data:
