version: '3.8'

services:
  # Serviço MongoDB com replicação
  mongo:
    image: mongo:6
    command: mongod --replSet rs0 --bind_ip_all --keyFile /data/keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
      - ./keyfile:/data/keyfile:ro
    networks:
      - mean_net
    deploy:
      replicas: 1

  # Serviço MongoDB (réplica 1)
  mongo_replica_1:
    image: mongo:6
    command: mongod --replSet rs0 --bind_ip_all --keyFile /data/keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_replica1_data:/data/db
      - ./keyfile:/data/keyfile:ro
    networks:
      - mean_net
    deploy:
      replicas: 1

  # Serviço MongoDB (réplica 2)
  mongo_replica_2:
    image: mongo:6
    command: mongod --replSet rs0 --bind_ip_all --keyFile /data/keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_replica2_data:/data/db
      - ./keyfile:/data/keyfile:ro
    networks:
      - mean_net
    deploy:
      replicas: 1

  # Serviço do backend (Node.js + Express)
  backend:
    build:
      context: ../backEnd
      dockerfile: dockerFile
    environment:
      MONGO_URL: mongodb://root:password@mongo:27017,mongo_replica_1:27017,mongo_replica_2:27017/meancrud?replicaSet=rs0
    networks:
      - mean_net
    depends_on:
      - mongo
      - mongo_replica_1
      - mongo_replica_2
    deploy:
      replicas: 2

  # Serviço do frontend (Angular)
  frontend:
    build:
      context: ../frontEnd  # Define o contexto para a pasta frontEnd
      dockerfile: dockerFile  # Certifique-se de que o nome está correto (dockerFile ou Dockerfile)
    ports:
      - "4200:80" # Porta do Angular em produção
    networks:
      - mean_net
    depends_on:
      - backend
    deploy:
      replicas: 1

networks:
  mean_net:
    driver: bridge

volumes:
  mongo_data:
  mongo_replica1_data:
  mongo_replica2_data:
